// Generated from the backend wire contract. Do not edit directly.
/** Canonical wire contract. Frontend copy is generated by scripts/sync-contracts.mjs. */
export const PROTOCOL_VERSION = 2;
export const RULE_VERSION = "skylo-2-positive-penalty";

export type Card = -2 | -1 | 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12;
export type Difficulty = "easy" | "medium" | "hard";
export type ParticipantRole = "player" | "spectator";
export type GamePhase = "reveal two cards" | "pick up card" | "place card" | "reveal card" | "new round" | "game ended";
export type BotConfig = { strategyId: string; difficulty: Difficulty; version?: string };
export type PlayerSpec = { id: string; name: string; kind: "human" | "bot"; botConfig?: BotConfig };
export type GameAction =
  | { type: "reveal"; slotId: string }
  | { type: "place"; slotId: string }
  | { type: "draw" }
  | { type: "take-discard" }
  | { type: "discard" }
  | { type: "next-round" };
export type PlayerView = PlayerSpec & {
  deck: [Card | null, Card | null, Card | null][];
  slotIds: [string, string, string][];
  knownCardPositions: [boolean, boolean, boolean][];
  playersTurn: boolean;
  cardCache: Card | null;
  tookDispiledCard: boolean;
  roundPoints: number;
  totalPoints: number;
  closedRound: boolean;
  place: number | null;
};
export type EndReason = "point-limit" | "round-limit" | "action-limit" | "aborted";
export type CoreView = {
  protocolVersion: number;
  ruleVersion: string;
  matchId: string;
  sessionId: string;
  revision: number;
  turn: number;
  round: number;
  phase: GamePhase;
  playerCount: number;
  players: PlayerView[];
  activePlayerId: string | null;
  cardStack: { cards: null[] };
  discardPile: Card[];
  endReason: EndReason | null;
};
export type PlaybackState = { delayMs: number; paused: boolean; stepping: "action" | "turn" | null; thinking: boolean };
export type DecisionSummary = { playerId: string; explanation: string; decisionMs: number; fallback: boolean };
export type GameView = CoreView & {
  ownPlayerId: string | null;
  role: ParticipantRole;
  legalActions: GameAction[];
  decisionId: string | null;
  playback: PlaybackState;
  lastDecision: DecisionSummary | null;
};
export type PlayerObservation = CoreView & { ownPlayerId: string; legalActions: readonly GameAction[] };
export type GameEvent = { type: string; playerId?: string; data?: Record<string, unknown> };
export type ActionRequest = { sessionId: string; matchId: string; requestId: string; decisionId: string; action: GameAction };
export type PlaybackCommand = { type: "delay"; delayMs: number } | { type: "pause" | "resume" | "step-action" | "step-turn" };
export type SessionParticipant = { id: string; name: string; role: ParticipantRole; playerId: string | null };
export type SessionView = {
  protocolVersion: number;
  sessionId: string;
  hostId: string;
  ownParticipantId: string;
  ownPlayerId: string | null;
  role: ParticipantRole;
  maxPlayers: number;
  maxSpectators: number;
  players: PlayerSpec[];
  participants: SessionParticipant[];
  running: boolean;
  canControl: boolean;
  hasExport: boolean;
};
export type ResponseCode = "success" | "error:invalid" | "error:full" | "error:running" | "error:joined" | "error:membership" | "error:host" | "error:players" | "error:stale" | "error:rate-limited" | "error:finished";
